name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Hugging Face CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Deploy to Hugging Face
        env:
          HF: ${{ secrets.HF }}
        run: |
          echo "Using Hugging Face Token: $HF"
          make deploy HF=$HF
